# Generated by Django 5.2 on 2025-11-15 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baguettes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='abc123', max_length=128),
            preserve_default=False,
        ),
    ]
