# Generated by Django 5.2 on 2025-11-15 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baguettes', '0002_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='is_premium',
            field=models.BooleanField(default=False),
        ),
    ]
