# Generated by Django 5.2 on 2025-11-15 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baguettes', '0003_menuitem_is_premium'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
    ]
