# Generated by Django 5.2 on 2025-11-15 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baguettes', '0004_remove_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_premium',
            field=models.BooleanField(default=False),
        ),
    ]
