# Generated by Django 5.2 on 2025-12-02 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baguettes', '0007_alter_cartitem_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=64, unique=True)),
                ('task1_done', models.BooleanField(default=False)),
                ('task2_done', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='bad_password',
            field=models.CharField(default=':D', max_length=64, unique=True),
            preserve_default=False,
        ),
    ]
