# Generated by Django 5.2 on 2025-12-04 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baguettes', '0008_playerprogress_user_bad_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.IntegerField(unique=True)),
                ('flag', models.CharField(max_length=256)),
            ],
            options={
                'ordering': ['task_id'],
            },
        ),
    ]
