# Generated by Django 5.2 on 2025-12-05 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baguettes', '0009_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerprogress',
            name='task3_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='playerprogress',
            name='task4_done',
            field=models.BooleanField(default=False),
        ),
    ]
