# Generated by Django 5.2 on 2025-12-07 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baguettes', '0011_alter_menuitem_description_alter_menuitem_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='is_initiated_as_premium',
            field=models.BooleanField(default=False),
        ),
    ]
