# Generated by Django 5.2 on 2025-12-08 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baguettes', '0012_menuitem_is_initiated_as_premium'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('data', models.JSONField()),
            ],
        ),
        migrations.AddField(
            model_name='playerprogress',
            name='task5_disaster_triggered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='playerprogress',
            name='task5_done',
            field=models.BooleanField(default=False),
        ),
    ]
